# -*- coding: utf-8 -*-
"""chapter 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2nbrofdC_RWVuGyGxQ-LZ1uvMe0TJjm
"""

import pandas as pd
import numpy as np

# Load dataset
file_path = "/large_traffic_dataset.xlsx"
df = pd.read_excel(file_path)

# Define frame size (assuming 1280x720 resolution)
FRAME_WIDTH, FRAME_HEIGHT = 1280, 720

# Generate synthetic bounding boxes
np.random.seed(42)  # Reproducibility
synthetic_data = []

for index, row in df.iterrows():
    frame_number = np.random.randint(1, 108000)  # 30 FPS * 3600 seconds (1 hour)

    x1 = np.random.randint(0, FRAME_WIDTH - 100)
    y1 = np.random.randint(0, FRAME_HEIGHT - 100)
    width = np.random.randint(30, 100)
    height = np.random.randint(30, 100)
    x2 = x1 + width
    y2 = y1 + height
    confidence = round(np.random.uniform(0.6, 1.0), 2)

    synthetic_data.append([frame_number, row["Vehicle Type"], x1, y1, x2, y2, confidence])

# Convert to DataFrame
synthetic_bbox_df = pd.DataFrame(synthetic_data, columns=["Frame", "Vehicle Type", "x1", "y1", "x2", "y2", "Confidence"])

# Save synthetic data
synthetic_bbox_df.to_csv("/home/synthetic_traffic_data.csv", index=False)

# Display sample data
synthetic_bbox_df.head()